# Generated by Django 5.2.8 on 2025-12-05 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mouvementstock",
            name="entrepot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.entrepot",
            ),
        ),
        migrations.AddField(
            model_name="vente",
            name="entrepots",
            field=models.ManyToManyField(blank=True, to="users.entrepot"),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="type_mouvement",
            field=models.CharField(
                choices=[
                    ("entree", "Entrée en stock"),
                    ("sortie", "Sortie de stock"),
                    ("ajustement", "Ajustement"),
                    ("transfert", "Transfert entrepôt"),
                ],
                max_length=20,
            ),
        ),
    ]
