# Generated by Django 5.2.8 on 2025-12-20 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_mouvementstock_entrepot_vente_entrepots_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vente",
            name="date_echeance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vente",
            name="date_paiement",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vente",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("especes", "Espèces"),
                    ("carte_bancaire", "Carte bancaire"),
                    ("cheque", "Chèque"),
                    ("virement", "Virement"),
                    ("mobile_money", "Mobile Money"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vente",
            name="montant_paye",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="vente",
            name="montant_restant",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="vente",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vente",
            name="statut_paiement",
            field=models.CharField(
                choices=[
                    ("non_paye", "Non payé"),
                    ("partiel", "Payé partiellement"),
                    ("paye", "Payé"),
                    ("retard", "En retard"),
                ],
                default="non_paye",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_facture", models.CharField(max_length=50, unique=True)),
                ("date_facture", models.DateField(auto_now_add=True)),
                (
                    "montant_ht",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pdf_facture",
                    models.FileField(blank=True, null=True, upload_to="factures/"),
                ),
                ("envoye_email", models.BooleanField(default=False)),
                ("date_envoi", models.DateTimeField(blank=True, null=True)),
                (
                    "vente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facture",
                        to="users.vente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("carte_bancaire", "Carte bancaire"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("date_paiement", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="users.vente",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_paiement"],
            },
        ),
    ]
